[package]
name = "WorkTime"
version = "0.1.0"
authors = ["PotatoNinja92"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"

[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]
